# Generated by Django 6.0.3 on 2026-03-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_section_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='program',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.CharField(default='General Subject', max_length=150),
        ),
        migrations.AddField(
            model_name='section',
            name='year_level',
            field=models.CharField(default='1st Year', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
