# Generated by Django 6.0.3 on 2026-03-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assessment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('Essay', 'Essay'), ('Coding', 'Coding'), ('Multiple Choice', 'Multiple Choice'), ('Identification', 'Identification'), ('Enumeration', 'Enumeration'), ('True or False', 'True or False')], default='Essay', max_length=50),
        ),
    ]
